import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import { Box, CssBaseline, Link, Typography } from "@mui/material";
import React from "react";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <Header />
        <main className={"centered-column-flex " + styles.main}>
          <Box className={styles.titlesBox}>
            <Link
              className="centered-column-flex"
              href="/"
              underline="hover"
              color="inherit"
            >
              <Typography variant="h4" component="h1">
                Visits
              </Typography>
              <Typography variant="subtitle1">
                Some descriptive subtitle here
              </Typography>
            </Link>
          </Box>

          {children}
        </main>
      </body>
    </html>
  );
}
