import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import { Box, CssBaseline, Link as MuiLink, Typography } from "@mui/material";
import React from "react";
import styles from "./layout.module.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <Header />
        <Box className={"centered-column-flex " + styles.titlesBox}>
          <MuiLink
            component={Link}
            className="centered-column-flex"
            href="/"
            underline="hover"
            color="inherit"
          >
            <Typography variant="h4" component="h1">
              Visits
            </Typography>
            <Typography variant="subtitle1">
              Some descriptive subtitle here
            </Typography>
          </MuiLink>
        </Box>

        <main className={"centered-column-flex " + styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
